### ISSUE TITLE
ajax validation on an emongodocument

### ISSUE THREAD

**Issue by mesongo** [Sammaye/MongoYii#217]
ajaxvalidation on an emongodocument activerecord with an embedded document fails to return errors.

**Comment by Mesongo** [comment]
Collins wants you to check out Tenderpreneur.net
===============================================
 
Hi:

I would like to add you to my network on Tenderpreneur.net.

Follow this link to join my network:
http://tenderpreneur.net.

Have a great day!

Explore Tenderpreneur.net and create network of your friends.===============================================

App Uprising, Inc., 20 Jay street, Brooklyn, NY, 11201

Powered by ReadyGraph
https://www.readygraph.comIf you'd like to unsubscribe and stop receiving these emails click here: http://email.readygraph.com/wf/unsubscribe?upn=s5UH8bhnBaopYjthcNSRcVDlpAn9ZhdeU3MU2sgV-2BikIM4LRxT-2BuhPg4XrW-2B-2F9umCmrokSBA4NkJVi7OnXJvPftlxiuJk6WJUlab-2Fsf1YezLmZ8x-2Fhf5-2FuHmo60zHChwNDxC29bBY3hl4MAzZ-2Ft9IuO7PaH3Q0kYxwLqB22ayS3wGxmIKrn6cxvXdzqJZvoPc0jKsbhqlVRYImtvDdiFiKR4C0lyVNth21dRRtFtTNl36CXGXUqUBbHKrlobPv8vHHlHtSqPo0YrbGL8GC7-2FGi2fsIucdyKMIFDOHpTGcvoDNL-2FE-2B7QccyxwDajm5wkWrmKVBwhSR8dgRo4PjyXiFg-3D-3D.

**Comment by Mesongo** [comment]
Hi,

I&#39;d like to add you to my professional network on LinkedIn.

- Mesongo

Accept: https://www.linkedin.com/blink?simpleRedirect=0Mc3wMc3kPd34Nd3gSczASe3ARfkh9rCZFt65QqnpKqipedBxMm6xDkjRVpkJApn9xq7cCt7dBtmtvpnhFtCVFfmJB9C5QoORBt6BSrCAJt7dBtmsJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9D0PbnlUcnlEsjtFbmlDpmJOczRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5986926486869807106_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=s3cJtnwNtmxNdSAJpmtBqT8OfmhFpipppAZcgQhWc6FjtnwUgmZml5BnkRxGglBhtCBnhQNmmj96k6Vnd6p8lmpQi4NSdQRNcSdKh6JIclBOdTEVjQxpdCpjundfj31fmkpMd4lCmCoVsTkRuBp5gCkQcTkOejBltSZCi4FIgQZQi6dcjAEOcBlqpDcSiCcJuCdfdkxShORDll1FcSZBikp7gB93lRxUlk51gmtjbkhzgSBkrl5fi551fmhFrSMCt7dBtmtvpnhFtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9D0PbnlUcnlEsjtFbmlDpmJOczRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5986926486869807106_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9D0PbnlUcnlEsjtFbmlDpmJOczRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5986926486869807106_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by Sammaye** [comment]
Please stop posting spam messages here

**Comment by Mesongo** [comment]
Mesongo Collins would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=c30Uc30RcPgNcjgQdz8VdzwVdjR4imVLqnhxt6BSrCACjzpos5xEpR4Zumlbp6lOomxP9DhUpnhvt71BoSdxfndQ9CZOpmwZrioPfmBI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9ClQqnpKimtBkClOs3Rx9DsPbmBOcmBzujtFbmlDpmJOczRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5986926486869807106_500&markAsRead=

View Mesongo Collins&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=0PcPkQd30NcP8Zh4BOpm9JpmQCt7xBt5ZBr6BCrT9MfndQ9CZOpmwZrioQfmBI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DpMrzRQ9DsPbmBOcmBzujtFbmlDpmJOczRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5986926486869807106_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6RLoQkO9m9Rq7hFpQkO9nBIs6lOc3gBdPsOe3kRd2QRp3ASc38Me3sToCoRoCgPp3gQpjhAcjkQejcQpmcVp3gPcS5zcjxybjgNdzgOejcPbmB2cylVr71BszRIqm5JpioMdz0MczRAqioMc3wMc3kPd34Nd3gSczASe3ARfmhFpOoNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpzRHpipQu6lQnS9RsSVRbjkJoDlPrDkJcj1vsClArCBJpn9vt7dBtmtvt7dOqmoJr6RBfmtKqmJzon9Q9CZLpPRQ9DsPbmBOcmBzujtFbmlDpmJOczRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5986926486869807106_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=7sPbmBOcmBzujtFbmlDpmJOczRAqmkCjjBBc4VJc555rPxOkSZvh54VlQVvu30JpkYVoQlIuj1vdkRVnQ5fc68JrApybmxOsDxks58Rr5legShCknhIhB1JsmdIs4pJoiQPckZygTh2rT5npn1eoSRpu35zmzx2h7tIekh8t4l4sPdooz1SpSx3gSZUhkoVq4lClAhodTcQnPdEuBBFrjgTbloOrRZWu5l1gk5Du4gVgPxasmsQkklhgjRAqmZI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9DsPbmBOcmBzujtFbmlDpmJOczRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5986926486869807106_500&amp;markAsRead=This email was intended for Sammaye/MongoYii. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=3wUdPgZp4BBr6dFt79x9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9DsPbmBOcmBzujtFbmlDpmJOczRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5986926486869807106_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA
