### ISSUE TITLE
Mongoyii extension to connect to mongodb

### ISSUE THREAD

**Issue by pareshgehlot** [Sammaye/MongoYii#250]
I am using Mongoyii extension to connect to mongodb, my connection code is as below

'mongodb' => array(
'class' => 'EMongoClient',
'server' => 'mongodb://123.456.7.890:12345',
'db' => 'dabatase'
),
I have different sections like section a, section b, section c, section d in my Yii application, preceded with login, to access those sections.

1.Now when I log into my application on login page, one connection is done to mongodb, which I am able to see in mongodb's log.

After logging, when I click on any of the sections, sometimes, it creates a new connection per section and sometimes not.
I am unable to find exact reason for the same.

I have several queries:

Ideal connection time out of mongoyii?

When I logout, I want to close all connections that YII app made, how can it be done?

If a connection is already done, YII app should check for the same, and use the same, rather than creating new connection. How this can be done?

**Comment by Sammaye** [comment]
Also here: http://stackoverflow.com/questions/29539896/mongoyii-opening-multiple-connections-php

**Comment by Sammaye** [comment]
I beleive this is answered on SO by explaining exactly7 how Apache and PHP handle fork per request
