### ISSUE TITLE
Update model after getting it from cache

### ISSUE THREAD

**Issue by Kison** [Sammaye/MongoYii#251]
I am use caching models in my project, and found that if i try update model after getting it from cache its fields will be rewrote. The reason is that EMongoClient do not have attribute names for ($_meta field in EMongoClient) model that is updated. Now think how best to fix it.

Save model to cache:
```php
$model  =  SomeModel::model()->findByPk(someMongoId);
Yii::app()->cache->set($cacheKey, $model, self::CACHE_PERIOD);
```

This code clears all document fields excepts fields that stored in $_attributes field of model
```php 
$model = Yii::app()->cache->get($cacheKey);
// Do some changes with model fields
$model->name = 'Den';
$model->surname = 'Kison';
$model->update();
```

**Comment by Kison** [comment]
Maybe have a reson to add setDocumentCache($model) in beforeSave method?

**Comment by Sammaye** [comment]
Your second comment seems like it could solve all conditions, not just ones where the fields exist in the document explicitly

**Comment by Sammaye** [comment]
we if I just add setDocumentCache at the start of before save it would solve it?

**Comment by Kison** [comment]
Now i solve problem by adding 

```php
$this->getDbConnection()->setDocumentCache($this);
```
At the start of beforeSave. Works without problems, but have doubts.

**Comment by Sammaye** [comment]
It should be fine, it will recache all the fields of the doc in that PHP process. There must a reason why this is not being called naturally on the init() of the model...
