### ISSUE TITLE
when use EMongoSort with EMongoDataProvider, not act as like CSort with CActiveDataProvider

### ISSUE THREAD

**Issue by Icedroid** [Sammaye/MongoYii#254]
```
public function search()
 {
        $criteria = new EMongoCriteria;
        $criteria->compare('name', $this->name);

        $sort = new EMongoSort();
        $sort->attributes = array(
            'startTime',
            'endTime',
            //'*', // this adds all of the other columns as sortable
        );
        $sort->defaultOrder = 't.startTime DESC';

        return new EMongoDataProvider(get_class($this), array(
            'criteria' => $criteria,
            'sort' => $sort,
            'pagination' => array('pageSize' => 15),
        ));
}
```

I want only startTime and endTime attributes be sortable in CGridView. But It doesn't done as the CSort do.

**Comment by Sammaye** [comment]
So you're saying that * is supposed to? Can you link documentation for that?

**Comment by Icedroid** [comment]
```
$sort->attributes = array(
            'startTime',
            'endTime',
        );
```
These code take no effect.

**Comment by Sammaye** [comment]
Oops, I forgot all about this. It will take me sometime to test this since I have not checked out my MongoYii test repo in a long time (haven't used Yii1 in like a year so far) so I will need more time to find some spare time to work on this.

**Comment by Icedroid** [comment]
@Sammaye Thanks for your reply. Does you have moved to yii2?

**Comment by Sammaye** [comment]
Indeed I am totally on Yii2 these days

**Comment by Sammaye** [comment]
Ok, I finally got round to this and I notice that the code to sort by * does exist. Can you clarify what you mean by "But It doesn't done as the CSort do." can you tell me what the response is? What attributes are sortable?

**Comment by Sammaye** [comment]
Seems to work for me in my test repo: https://github.com/Sammaye/MongoYii-test/blob/master/protected/views/user/index.php#L30 despite the group field being sortable without defining any attributes in the data provider once I did it became unsortable: https://github.com/Sammaye/MongoYii-test/blob/master/protected/models/User.php#L86 and a default order was applied

**Comment by Icedroid** [comment]
```
$sort = new EMongoSort();
        $sort->attributes = array(
            'startTime',
            'endTime',
            //'*', // this adds all of the other columns as sortable
        );
        $sort->defaultOrder = array('endTime' => -1);

        return new EMongoDataProvider(get_class($this), array(
            'criteria' => $criteria,
            'sort' => $sort,
            'pagination' => array('pageSize' => 15),
        ));
```
It does not take effected.

**Comment by Sammaye** [comment]
OK that's done now, tested.

**Comment by Icedroid** [comment]
I update these fix version, the bug is fixed. But I found a new bug.
after use these code:
```
$sort = new EMongoSort();
        $sort->attributes = array(
            'startTime',
            'endTime',
            //'*', // this adds all of the other columns as sortable
        );
        $sort->defaultOrder = array('endTime' => -1);

        return new EMongoDataProvider(get_class($this), array(
            'criteria' => $criteria,
            'sort' => $sort,
            'pagination' => array('pageSize' => 15),
        ));
```
the following code not run like as before:
```
 public function attributeLabels()
   {
        return array(
            '_id' => 'ID',
        );
}
```

**Comment by Sammaye** [comment]
Are you defining the columns in your widget like so:
```php
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'user-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'_id',
		'username',
		'email',
		'group',
		array(
			'class'=>'CButtonColumn',
			'template'=>'{update}{delete}',
		),
	),
)); ?>
```
?

I have found out that if you define the columns then you must define the names for some odd reason. It comes down to the contents of CGridView:

	/**
	 * Creates column objects and initializes them.
	 */
	protected function initColumns()
	{
		if($this->columns===array())
		{
			if($this->dataProvider instanceof CActiveDataProvider)
				$this->columns=$this->dataProvider->model->attributeNames();
			elseif($this->dataProvider instanceof IDataProvider)
			{
				// use the keys of the first row of data as the default columns
				$data=$this->dataProvider->getData();
				if(isset($data[0]) && is_array($data[0]))
					$this->columns=array_keys($data[0]);
			}
		}
		$id=$this->getId();
		foreach($this->columns as $i=>$column)
		{
			if(is_string($column))
				$column=$this->createDataColumn($column);
			else
			{
				if(!isset($column['class']))
					$column['class']='CDataColumn';
				$column=Yii::createComponent($column, $this);
			}
			if(!$column->visible)
			{
				unset($this->columns[$i]);
				continue;
			}
			if($column->id===null)
				$column->id=$id.'_c'.$i;
			$this->columns[$i]=$column;
		}

		foreach($this->columns as $column)
			$column->init();
	}

	/**
	 * Creates a {@link CDataColumn} based on a shortcut column specification string.
	 * @param string $text the column specification string
	 * @return CDataColumn the column instance
	 */
	protected function createDataColumn($text)
	{
		if(!preg_match('/^([\w\.]+)(:(\w*))?(:(.*))?$/',$text,$matches))
			throw new CException(Yii::t('zii','The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.'));
		$column=new CDataColumn($this);
		$column->name=$matches[1];
		if(isset($matches[3]) && $matches[3]!=='')
			$column->type=$matches[3];
		if(isset($matches[5]))
			$column->header=$matches[5];
		return $column;
	}

So it seems this is a framework problem not an extension problem.
