### ISSUE TITLE
Can you please suggest how to use aggregate functions?

### ISSUE THREAD

**Issue by Viper177** [Sammaye/MongoYii#256]
Hi Sammaye,

I am working on a project where my problem leads me to have solution using an aggregate function in mongodb. I am unable to transform this query into Yii using your extension.  Below is my mongo query:

db.collectionName.aggregate({$match: {"_id": "36911613248"}}, { $unwind: "$following"}, {$match: {"following.content_id": { $regex: /^369/ }}}, {$skip: 0 }, { $limit: 5 }, { $group: { _id: "$_id", "following": { $push: "$following" }}})

Can you please suggest me the solution?

Regards,
Hemant

**Comment by Kison** [comment]
Hi, i guess it would be something like this
```php
Model::model()->aggregate([
    ['$match' => ["_id" => "36911613248"]],
    ['$unwind' => '$following'],
    ['$match' => ["following.content_id" => new MongoRegex('/^369/')]],
    ['$skip' => 0 ],
    ['$limit' => 5],
    ['$group' => ['_id' => '$_id', "following" => ['$push' => '$following']]]
]);
```

**Comment by Viper177** [comment]
Thanks a lot Kison. You saved my day.
