### ISSUE TITLE
Multiple databases

### ISSUE THREAD

**Issue by Kuzdo** [Sammaye/MongoYii#261]
Hello Sammaye again,

I had a problem with two DBs in one Action, because I was thinking, that I must override only getMongoComponent to working with multiple DBs. So, for what is that method? To working with multiple DBs I can only override getDbConnection, and all is fine, I don't must override getMongoComponent.

Regards.

**Comment by Kuzdo** [comment]
I read this: http://www.yiiframework.com/wiki/123/multiple-database-support-in-yii/ and there is no need to override getMongoComponent in my opinion.

What is the best method to run application with more DBs?

**Comment by Sammaye** [comment]
Sorry for the late response have been a bit busy.

In fact I implement those functions in the models: https://github.com/Sammaye/MongoYii/blob/master/EMongoModel.php#L595 so you can actually convert that tutorial to this extension.

I personally did not use multiple DBs with the application I made in Yii1

**Comment by Sammaye** [comment]
I am going to close this since I don't think there is much more to say actually

**Comment by Kuzdo** [comment]
> In fact I implement those functions in the models: https://github.com/Sammaye/MongoYii/blob/master/EMongoModel.php#L595 so you can actually convert that tutorial to this extension.

I don't understand what you mean. I was testing this for some time, and for now I know that there must be overriden method getDbConnection and we can access to multiple DBs. I do this like this:

 ```php
    public function getDbConnection()
    {
        return self::getMongoComponent();
    }

    public function getMongoComponent()
    {
        return Yii::app()->component;
    }
```

Idk if this is ok, and there will be no problems in future, for now is ok :)

**Comment by Sammaye** [comment]
Yeah, that's fine.

With what I said earlier what I mean is, taking from the tutorial directly:
```php
// protected/components/MyActiveRecord.php
 
class MyActiveRecord extends CActiveRecord {
    ...
    private static $dbadvert = null;
 
    protected static function getAdvertDbConnection()
    {
        if (self::$dbadvert !== null)
            return self::$dbadvert;
        else
        {
            self::$dbadvert = Yii::app()->dbadvert;
            if (self::$dbadvert instanceof EMongoConnection)
            {
                return self::$dbadvert;
            }
            else
                throw new EMongoException(Yii::t('yii','Active Record requires a "db" EMongoConnection application component.'));
        }
    }
```

and you should be able to follow the tutorial from there.

But your way is totally fine too

**Comment by Kuzdo** [comment]
Ok, thanks :)
