### ISSUE TITLE
EMongoDocument has no refreshMetaData method.

### ISSUE THREAD

**Issue by Kuzdo** [Sammaye/MongoYii#262]
Hello again (I know, I'm annoying :D),

EMongoDocument has no refreshMetaData method like CActiveRecord, but maybe there is other method which do that what do refreshMetaData from CActiveRecord.

Why I'm searching this method? Because I need to create Model with dynamic name of collection. One of the solutions is using field with name of collection, collectionName returns that field, and after each change of that field we need refresh meta data in model. There is more info: https://stackoverflow.com/questions/10186563/yii-models-using-dynamic-table-name-in-a-yii-model

And I don't know if I can put that method (from CAR) directly to my model or I should use some other method?

Regards

**Comment by Sammaye** [comment]
Since MongoYii has no meta data I removed the function and it doesn't need to be used

**Comment by Kuzdo** [comment]
Ok, big thanks for response :)
