### ISSUE TITLE
Probably wrong sort order.

### ISSUE THREAD

**Issue by Kuzdo** [Sammaye/MongoYii#263]
Hello again,

In my model I have defaultScope method and scopes. In defaultScope I have sorting by _id => 1 and in custom scope I have sorting by name => 1 and _id => -1, but when I use this scope, query to mongo still is with sort _id => -1, name => 1 instead name => 1, _id => -1. I think, the new scope should override sort data if there is field which was already in sorting.

```php
public function defaultScope() {
	return [
		'sort' => ['_id' => 1]
	];
}

public function scopes() {
	return [
		'byName' => [
			'sort' => ['name' => 1, '_id' => -1]
		]
	];
}

....

Model::model()->byName()->find();

....
Log from mongodb:
query: { $query: {}, $orderby: { _id: -1, name: 1 } }
```

I think, that there should be also method to clear sorting, because I don't want sorting by _id in byName scope.

Regards.

**Comment by Kuzdo** [comment]
Also, defaultScope is always included to query. I don't know if that should be in that way. In my opinion defaultScope should be included only when no other scope is provided, but I'm not expert in Yii :D 

```php
public function defaultScope() {
	return [
		'sort' => ['_id' => 1]
	];
}

public function scopes() {
	return [
		'byName' => [
			'sort' => ['name' => 1]
		]
	];
}

....

Model::model()->byName()->find();

....
Log from mongodb:
query: { $query: {}, $orderby: { _id: 1, name: 1 } }
```

**Comment by Sammaye** [comment]
This is how it worked last time I checked in Yii.

The easiest way around is to call resetScope(), changing this functionality may cause bugs in other people's programs right now, this is very old functionality

**Comment by Kuzdo** [comment]
So, the best way for do what I want is implement custom scope with resetScope like this?
```php
public function byName() {
    $this->resetScope();
    $this->mergeDbCriteria([
        'sort' => ['name' => 1]
    ]);
    return $this;
}
```

And for what is resetScope(true)? I see that, criteria will be array instead of null, but what that changes?

**Comment by Sammaye** [comment]
Yeah basically

**Comment by Sammaye** [comment]
Putting true in the first param will stop the default scope from being applied at a later time

**Comment by Kuzdo** [comment]
Ok, thanks for answer :)
