### ISSUE TITLE
Upgrade to new PHP MongoDB driver

### ISSUE THREAD

**Issue by Sammaye** [Sammaye/MongoYii#266]
- [x] Setup new environment from https://github.com/Sammaye/MongoYii/issues/265
- [x] Take a look at http://php.net/manual/en/set.mongodb.php and understand what needs doing
- [x] What about GridFS?
- [x] Implement namespaces
- [x] Move w options etc to be per database and not in the client (even though this means you will need to define w etc for every database it is the right thing to do semantically)
- [x] Move the profile logging to a global Collection class so that every query and can logged
- [x] Remove DBRef from ext as they have now been deprecated
- [x] Rewrite all query method to use the Query class like in Yii2 now
- [x] Implement SPL cursor to fix problems with using Yii1/2 (both) with new driver https://secure.php.net/manual/en/class.mongodb-driver-cursor.php#118824
- [x] Make all cursors eager now (the driver has changed to make all cursors eager loading)
- [x] Change the database working in EMongoDocument to be more reliable and robust (stop using n and nModified for example)
- [x] Make sure to use string ids for the session management due to https://jira.mongodb.org/browse/PHPC-460
- [x] Add auth

**Sections**

- [x] Client
- [x] Session
- [x] Cache
- [x] Database
- [x] Collection
- [x] ExistValidator
- [x] UniqueValidator
- [x] MongoIdValidator
- [x] SubdocumentValidator
- [x] AuthManager
- [x] Migration (both files)
- [x] Messages
- [x] Pagination
- [x] TimeStampBehavior
- [x] LogRoute
- [x] Query (Was EMongoCriteria)
- [x] Model
- [x] DataProvider
- [x] Document
- [x] Cursor
- [ ] File

**EMongoDocument functions needing complete rewrite**
All other functions should be considered as working (if not needing a little work when testing the ext out more)

- [x] findOne()
- [x] find()
- [x] getDbCriteria() entire workings
- [x] Line 1097
- [x] mergeDbCriteria

**Tests**

- [x] Rewrite test App
- [x] Rewrite tests folder

**Packaging**

- [x] Package in a namespace
- [x] Test to make sure that namespace works in Yii1
- [x] Add to composer

**Documentation**
- [x] Make a note about using multiple databases
- [x] Show how to define the ext now
- [x] Note bout separation between client and collection in new driver
- [x] Note about change in Query, which is the part of the ext which deviates from Yii1 (closer to Yii2)
- [x] Note about how the driver returns subdocuments as BSON Documents that needs array typing

**Comment by Sammaye** [comment]
GridFS is forthcoming as such it will not be included unless I complete this after they have released it

**Comment by Sammaye** [comment]
Consider moving to teamwork pm where it is easier to manage than in Github

**Comment by Sammaye** [comment]
The cursor has changed so much it will require a fundamental rewrite of how querying in the ext works

**Comment by Sammaye** [comment]
Got a prototype cursor written, next is to link it in with querying

**Comment by Sammaye** [comment]
Don't ask me how but it seems I have prototype querying working

**Comment by Sammaye** [comment]
Poop, well it seems it is ready for me to rewrite my test app fully and start actually seeing if it works...

**Comment by Sammaye** [comment]
HAHAHAHA I cannot even complete my test app thanks https://jira.mongodb.org/browse/PHPC-460

**Comment by Sammaye** [comment]
I might be able to work around this, still early days but I think I can make Yii work with string _id

**Comment by Sammaye** [comment]
App 90% done

**Comment by Sammaye** [comment]
Great, due to how auth works in the new driver I have rewrite the whole of the client class again...

**Comment by Sammaye** [comment]
Actually I am going to keep it the way it is since it seem the auth db is actually logically separated from the data db

**Comment by Sammaye** [comment]
Just got the document tests left

**Comment by osamayawar** [comment]
So is it updated now?

**Comment by osamayawar** [comment]
Also, is there any quick way to migrate from older version to new one?

**Comment by Sammaye** [comment]
Indeed, except for EMongoFile, that's simply not there yet in the PHPLib.

The returns and everything for all the functions are the same, except for the deprecation of DBRef so adding the namespace changes allowed me to upgrade my test app in like 3 hours for the entire of it.

So it shouldn't be too hard.

One hard bit is if you are using the cursor directly in places, you will need to change that to Query now due to how the driver itself no longer supports that kind of working on the cursor.

**Comment by Sammaye** [comment]
Make sure you use the new repo as well https://github.com/Sammaye/mongoyii-php7 this will continue to be the legacy repo
