### ISSUE TITLE
Not able to find sub-document array within a particular date range.

### ISSUE THREAD

**Issue by Adi143** [Sammaye/MongoYii#267]
Hello Sammaye,

Plugin developed by you & your team is great.
I am currently working on a Yii1.0.

But not able to get expected result from your plugin, tried 

1.aggregate-projection,
2.simple find query, 
3.aggregate.

Best Possible tries:

1. db.collection.findOne({"user_email":"abc@xyz.com"},{_id:0 ,events: {$elemMatch : {sum:120} }})

2.db.collection.find({events:{$elemMatch: {$and:[{date:{$gte: new ISODate("2016-06-13T00:00:00Z")}},{date:{$lte: new ISODate("2016-06-20T23:00:00Z")}}]}}})

3. $start = new MongoDate(strtotime("2016-06-13 00:00:00"));
 $end = new MongoDate(strtotime("2016-06-20 23:59:00"));
 $model = $collection->find(array("events"=> array('$gt' => $start, '$lte' => $end)));

4.db.collection.aggregate([{$project:{"events.date": ISODate("2016-05-31T07:01:12.218Z") }}])

I have a document structure like:- 
{
    "_id": ObjectId("575912d631b9a4457891d"),
   "user_email":"abc@xyz.com",
    "events": [
    {
            "sum" : 10;
            "mul" : 100;
            "date": ISODate("2016-06-13T06:55:18.004Z")
    },
    { 
            "sum" : 20;
            "mul" : 10;

            "date": ISODate("2016-06-15T06:56:02.810Z")
    },
    { 
            "sum" : 20;
            "mul" : 10;

            "date": ISODate("2016-06-15T07:56:02.810Z")
    },
    { 
            "sum" : 20;
            "mul" : 10;

            "date": ISODate("2016-06-18T06:56:02.810Z")
    },
    { 
            "sum" : 120;
            "mul" : 10;

            "date": ISODate("2016-06-20T06:56:02.810Z")
    },
  { 
            "sum" : 120;
            "mul" : 10;

            "date": ISODate("2016-06-20T06:56:02.810Z")
    },
  { 
            "sum" : 120;
            "mul" : 10;

            "date": ISODate("2016-06-19T06:56:02.810Z")
    }
]
}
{...n no.of objects......

My Question are:-
1.How to fetch all sub-document array (events) from date 2016-06-13 to 2016-06-20 with the help of your plugin?
2. If sub-document array have same date ,how to get average of  'sum' field for particular day in one go,instead of foreach & then comparing each date(because there are no. of sub-array in events)?

**Comment by Sammaye** [comment]
You would use the aggregation framework for this. That is the supported way in MongoDB.

Your 4th idea was close but not enough. You need to $unwind and then $match and then $push/$addToSet
