### ISSUE TITLE
Add support for newer mongodb PHP driver

### ISSUE THREAD

**Issue by tomfotherby** [Sammaye/MongoYii#270]
The PHP mongo driver (`mongo` - https://pecl.php.net/package/mongo) is DEPRECATED. It'd be great if this Yii extension supported the replacement driver:  `mongodb` - https://pecl.php.net/package/mongodb

For example, The new official hosted mongodb service (*atlas*) only supports the newer PHP driver for the latest versions of mongo - source: https://docs.mongodb.com/ecosystem/drivers/php/#mongodb-compatibility

**Comment by Sammaye** [comment]
Over here https://github.com/Sammaye/mongoyii-php7
