### ISSUE TITLE
Authentication with different db

### ISSUE THREAD

**Issue by yelunightroad** [Sammaye/MongoYii#272]
i connect mongo with shell like this "./mongoimport --host=xxx --port=xxx -umongo -pxxx --authenticationDatabase=admin -d test" auth with admin db but connect to test db, how can i imply this in mongoYii?

**Comment by Sammaye** [comment]
I provided some explanation here https://github.com/Sammaye/MongoYii/issues/207#issuecomment-262758909

Basically the structure of this ext was made before the new roles and auth which means to change it now would cause massive BC breaking from what I see.

The PHP7 edition of this ext has it

**Comment by yelunightroad** [comment]
thanks, i use getConnection() and then change the database to solve this
