### ISSUE TITLE
not able to connect with atlas server.

### ISSUE THREAD

**Issue by neerajprashar** [Sammaye/MongoYii#276]
I created an atlas cluster and now trying to connect with it using this plugin in Yii framework. I'm getting `No candidate servers found` error even after putting correct connection string. Any help will be appreciated.

**Comment by Sammaye** [comment]
Since Yii1 has reached end of life, and I have not used Yii1 in years I am not sure how much I can help, tbh this extension uses a version of the PECL driver that's deprecated as well. 

But I can't really help with this, I simply don't use the tools anymore
